FROM docker.io/library/ruby:3.2.2-alpine3.18

WORKDIR /app

COPY . .
RUN \
  gem install bundler --version "2.4.21" && \
  BUNDLE_WITHOUT=development bundle install && \
  rm -f /usr/local/bundle/bin/imap-backup
ENV PATH=${PATH}:/app/bin

CMD ["imap-backup", "backup", "-c", "/config/imap-backup.json"]
