ARG RUBY_VERSION
FROM docker.io/library/ruby:$RUBY_VERSION-buster

ARG BUNDLER_VERSION=2.4.22

# Install dependencies
RUN \
  apt-get update && \
  apt-get install --yes less libffi-dev vim-nox

# Show full path in prompt
RUN echo 'PS1='\''imap-backup:$(pwd)>'\''' > /etc/bash.bashrc

# Create binstubs (including one for imap-backup) so we can run it
# without using `bundle exec`
ENV PATH /app/bin/stubs:$PATH

WORKDIR /app

RUN gem install bundler --version=$BUNDLER_VERSION

ENTRYPOINT ["bash"]
