# imap-backup built with different ruby versions for testing
version: "3"

services:
  imap-backup:
    build:
      context: ../
      dockerfile: dev/container/Dockerfile
      args:
      - RUBY_VERSION
    image: imap-backup:${RUBY_VERSION}
    user: $(id -u)
    environment:
    - DOCKER_HOST_IMAP=imap
    - DOCKER_PORT_IMAP=8993
    - DOCKER_HOST_OTHER_IMAP=other-imap
    - DOCKER_PORT_OTHER_IMAP=9993
    volumes:
      - ./dev/container:/app