FROM ruby:2.7.6-buster

# Install dependencies
RUN \
  apt update && \
  apt install --yes libffi-dev


RUN gem install bundler --version=2.1.4

RUN mkdir /app
WORKDIR /app
COPY Gemfile .
COPY imap-backup.gemspec .
COPY Gemfile.lock .
COPY lib lib
RUN bundle install
COPY . .

ENTRYPOINT ["bash"]
