FROM ruby:2.6.10-buster

# Install dependencies
RUN \
  apt update && \
  apt install --yes libffi-dev

# Run as an unprivileged user
RUN \
  mkdir /app && \
  groupadd -r user && \
  useradd --system --create-home --gid user user && \
  chown user: /app

WORKDIR /app
USER user

RUN gem install bundler --version=2.1.4

COPY Gemfile .
COPY imap-backup.gemspec .
COPY lib/imap/backup/version.rb lib/imap/backup/version.rb

RUN bundle install

COPY . .

ENTRYPOINT ["bash"]
