name: Tests

on:
  push:
    branches:
      - main
      - feature/*

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        rubygems: 3.0.3
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
    - name: Read Coverage
      run: |
        echo "COVERAGE=$(cat coverage/coverage_percent.txt)%" >> $GITHUB_ENV
    - name: Create Coverage Badge
      if: ${{ github.ref == 'refs/heads/main' && matrix.ruby == '3.2' }}
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.BADGES_GIST_ACCESS }}
        gistID: b54fe758bfb405c04bef72dad293d707
        filename: coverage.json
        label: Coverage
        message: ${{ env.COVERAGE }}
        color: brightgreen

    services:
      imap:
        image: ghcr.io/joeyates/docker-imap-devel@sha256:6d6a64c32e2c583222d75286aa46a04ada5aea76efa36117815bf0e19d5063b6
        ports:
        - "8993:993"
        env:
          MAILNAME: example.com
          MAIL_ADDRESS: address@example.com
          MAIL_PASS: pass
      other-imap:
        image: ghcr.io/joeyates/docker-imap-devel@sha256:6d6a64c32e2c583222d75286aa46a04ada5aea76efa36117815bf0e19d5063b6
        ports:
        - "9993:993"
        env:
          MAILNAME: other.org
          MAIL_ADDRESS: email@other.org
          MAIL_PASS: pass
          DOVECOT_PUBLIC_NAMESPACE_PREFIX: other_public
